version: '3.9'

services:
  app:
    build: .
    # image: ghcr.io/yude/np2mast:master
    volumes:
      - type: bind
        source: "./.env"
        target: "/bin/.env"
    restart: unless-stopped
    ports:
      - 3000:3000
  
